### ISSUE TITLE
Configure MQTT connection options

### ISSUE THREAD

**Issue by emmanuelsilva** [lopidio/enqueuer#4]
### Description

I'd like to test the message driven components of my IoT platform, but the communication between my components is entirely based on MQTT over SSL (MQTTS). 

Maybe it would be interesting if I could override the MQTT connection options when writing my JSON configuration file.

### Example of a configuration file using MQTTS:

In the follow JSON configuration example, I can configure the connection options (the properties names are based on [MQTT.JS project](https://github.com/mqttjs/MQTT.js)) to customize my MQTT broker connection, setting these properties to be able to open a security connection:

```
"publisher": {
  "type": "mqtt",
  "connect_options": {
      "key": "<string content of the Key PEM file>",
      "cert": "<string content of the Certificate PEM file>",
      "ca": "<string content of the CA pem file>",
      "protocol": "ssl",
      "port": "8883",
      "address": "<host>"
  },
  "payload": 100,
  "topic": "enqueuer/input"
}
```

**Comment by lopidio** [comment]
Sure.
Actually, you should be able to do this in this version using [MQTT.JS](https://github.com/mqttjs/MQTT.js) names.
Like this: 
>     "publisher": {
>       "type": "mqtt",
>       "brokerAddress": "mqtts://localhost",
>       "payload": "somethingCool",
>       "topic": "somethingCooler",
>       "options": {
>         "clientId": "enqueuerPublishOptionsExampleId",
>         "key": "<string content of the Key PEM file>",
>         "cert": "<string content of the Certificate PEM file>",
>         "ca": "<string content of the CA pem file>",
>         "protocol": "ssl"
>       }

Please, note that brokerAddress uses **mqtts** protocol.
Make sure to enable mqtt feature before doing this, ok?
`$npm run enable-feature mqtt`

**Comment by emmanuelsilva** [comment]
These configurations let me able to write my integration tests with enqueuer with MQTTS. Thank you @lopidio!
